### ISSUE TITLE
Firefox freezes intermittently unless the extension is disabled/removed

### ISSUE THREAD

**Issue by dharmit** [samueljun/tomato-clock#71]
**Describe the bug**

I'm **not** sure that this extension is the reason for the freeze I'm observing on Firefox but I don't see a way of being sure about it other than opening an issue. So, kindly do not take this as if I'm blaming the extension. On the contrary I love the extension and it has given me insights on my working pattern and made me think how I can work better.

When I start a pomodoro cycle, Firefox freezes randomly after some time and becomes completely unresponsive to mouse or keyboard inputs. This goes on for quite a few seconds and then Firefox becomes usable once again without changing anything on the system. I have started facing this issue since about a week.

**To Reproduce**
1. Start a pomodoro cycle and wait for some time

**Expected behavior**
Firefox should not freeze

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Browser [e.g. chrome, safari]: Firefox
    ```sh
    $ firefox -v
    Mozilla Firefox 68.0.2
    ```

**Additional context**
- The reason I **think** that this extension has something to do with the freeze is because I don't experience the issue if I disable/remove the extension. 
- I'm not sure how I can provide the logs or any other info that might be helpful. So, please let me know what info you might need from me.
- The extension is set to auto-update (default settings) so it's using the latest available version.

**Comment by dharmit** [comment]
A recent observation: pomodoro cycle doesn't need to be in progress for the issue to happen.

When I started facing this issue, I tried to isolate its cause by disabling all extensions and enabling them again one after the other till the issue surfaces.

**Comment by samueljun** [comment]
Closing since it sounds like it's something else, feel free to reopen if it's something with the extension.

**Comment by whym** [comment]
I experienced similar freezes constantly. It might have to do with Firefox Sync with a somewhat large timeline data (I think tens of kilo bytes) on Tomato Clock - my current workaround is to disable syncing addons. See below for more.

@dharmit: Do you have Firefox Sync enabled? If your Firefox recovers after a freeze, could you try openning `about:sync-log` and check the content of the newest file? You might see a line containing "ERROR	Syncing jid1-Kt2kYYgi32zPuw@jetpack" there. If so, I thik we are experiencing the same thing.

Here is one of the errors I got:

`1573020187874	Sync.Engine.Extension-Storage	ERROR	Syncing jid1-Kt2kYYgi32zPuw@jetpack: request failed: Error: Timeout while trying to access https://webextensions.settings.services.mozilla.com/v1/batch with {"method":"POST","headers":{"Accept":"application/json","Content-Type":"application/json","Authorization":"**** (suppressed)"},"body":"{\"defaults\":{\"headers\":{\"Authorization\":\"Bearer 688dec51a1e8309ba5a3d620a2a47260197a9081f3025020776ecb10f0ec5aa3\"}},\"requests\":[{\"method\":\"PUT\",\"path\":\"/buckets/default/collections/ext-5jGil0jc6a52idyb0ROW9UR0KWtnS6LW_fmP-VAMTMo/records/id-zm-k9x-E_uT_mU4xXhVNu_r7qCV9VqOlFvk1dYLWs38\",\"headers\":{\"If-Match\":\"\\\"1523430040159\\\"\"},\"body\":{\"data\":{\"ciphertext\":`

(I cut the above line after "ciphertext" - the rest seemed just ... tens of kilo bytes of encrypted data.)

I tried disabling Firefox Sync for addons, and the problem disappeared as far as I can see. (which is my current workaround, as I personally don't need addon settings to be synced at the moment.) No error was shown in `about:sync-log` after that.

Since the error says "Insufficient Storage", could it be the case that the timeline data is too large to be synced? My Tomato Clock export is somewhere around 42 kilo bytes, which is apparently larger than the quota written in https://bugzilla.mozilla.org/show_bug.cgi?id=1413949#c5 . I don't know how it could result in hanging up the browser, though.

**Comment by dharmit** [comment]
> @dharmit: Do you have Firefox Sync enabled? If your Firefox recovers after a freeze, could you try openning about:sync-log and check the content of the newest file?

I'm not facing the freeze issue anymore. But I do see an error similar to yours in the `about:sync-log`. However, it doesn't freeze the browser anymore.
